print("today is a good weather")
# today is a good weather
print ("today is a good weather","today is a bad weather", sep="/")
print("today is a good weather\n", end="???")
print ("\ntoday is a good weather", "today is a bad weather", sep="___", end="!!!")
print("\n#########")
print('#', "\t\t#")
print('#', "\t\t#")
print('#', "\t\t#")
print("#########")
print('#', "\t\t#")
print('#', "\t\t#")
print("#########")
print('#', "\t\t#")
print('#', "\t\t#")